services:
  api:
    environment:
      - ASPNETCORE_URLS=http://+:80
      # ÖNEMLİ: API, veritabanına "db" host adı ile bağlanmalı (Docker servis adı)
      - ConnectionStrings__DefaultConnection=Host=db;Database=planca;Username=postgres;Password=postgres
    ports:
      - "7000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    restart: on-failure

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planca_dev
    restart: on-failure