services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80  # Sadece HTTP kullan, HTTPS kaldırıldı
      # Sertifika ayarlarını kaldırıyoruz
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=planca
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=db;Database=planca_dev;Username=postgres;Password=postgres
    ports:
      - "7000:80"     # Sadece HTTP portu
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # HTTPS sertifika bağlantısını kaldırıyoruz
      # - ${APPDATA}/ASP.NET/Https:/https:ro
    restart: on-failure
    depends_on:
      - db
  
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planca_dev