services:
  api:
    build:
      context: .
      dockerfile: Planca.API/Dockerfile
    # Eğer burada port tanımları varsa, bunları silin veya düzeltin
    # ports:
    #   - "7000:80"
    #   - "7001:443"
    depends_on:
      - db
    networks:
      - planca-network
      
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - planca-network

networks:
  planca-network:
    driver: bridge
    
volumes:
  postgres-data: